### ISSUE TITLE
VS Code plugin does not seem to connect to local container

### ISSUE THREAD

**Issue by netcicd** [cisco-developer/api-insights#79] opened 2023-02-11 13:31 UTC
I installed as per the manual: clone repo, docker-compose up; installed the plugin and connected to the docker container. In VSCode it looks like it connected, but there is no response and there seems to be no interaction between vscode and the container as showed on CLEU

**Comment by npateriya** [comment] 2023-02-14 22:59
Can you please share a screenshot of the behavior you are noticing?

Please ensure API exposed on port 8081 as in https://developer.cisco.com/docs/api-insights/#!using-the-api-insights-visual-studio-code-extension/using-the-api-insights-extension-for-visual-studio-code step pre-requisite. 

Also can you please share a screenshot of VSCode extension setting mainly endpoint URL 
<img width="641" alt="Screenshot 2023-02-14 at 2 56 57 PM" src="https://user-images.githubusercontent.com/5516389/218882107-fc052d76-0b2c-48bc-96cb-e8a3beef8d6b.png">

**Comment by netcicd** [comment] 2023-02-15 08:03
Neelesh, it looks like the docker-compose install is different. 
I get all kinds of kubectl errors, and the port is 3000, not 8081. 
![Screenshot from 2023-02-15 08-59-10](https://user-images.githubusercontent.com/46484069/218967786-bcd4dd31-42f7-4fb7-a322-ce49284876cd.png)

**Comment by myref** [comment] 2023-02-17 07:53
after rebooting my PC several times, I now get the APIinsights plugin to report the status and I can view the report. If I open it in the editor I cannot edit however. Is that as planned?

**Comment by myref** [comment] 2023-02-17 09:05
I did a docker system prune -f and made sure all is clean before installing. It looks like the UI does not detach when running docker-compose up. It does not restart after rebooting the laptop. A clean install of the vscode plugin with the indicated settings gives a 405 error on opening of a file.

**Comment by npateriya** [comment] 2023-02-22 23:27
@hhxiaoatcisco  @xiaobao-shi can you please reproduce & debug this issue.

**Comment by shixiaobao17145** [comment] 2023-03-01 05:43
@myref  Is the issue remains? Did it work after you reinstall the extension?

**Comment by myref** [comment] 2023-03-01 07:50
I am on pto this week. Can try next weekVerstuurd vanaf mijn iPhone.Op 1 mrt. 2023 om 06:44 heeft Bob ***@***.***> het volgende geschreven:﻿
@myref  Is the issue remains? Did it work after you reinstall the extension?

**Comment by netcicd** [comment] 2023-03-02 13:19
I will try next week, I am on PTO at the moment and do jot have access to my laptopMarkVerstuurd vanaf mijn iPhone.Op 1 mrt. 2023 om 06:44 heeft Bob ***@***.***> het volgende geschreven:﻿
@myref  Is the issue remains? Did it work after you reinstall the extension?

**Comment by netcicd** [comment] 2023-03-06 08:02
reinstalled the extension, pulled and did docker-compose-up. Get "Request failed with status code 405"

**Comment by xinjixi** [comment] 2023-03-06 12:11
Hi @netcicd ,

Just tried to reproduce the issue. Seems it works as expected for me. Can you pls try:
1. Pull latest https://github.com/cisco-developer/api-insights
2. Start API Insights:
    ```shell
    cd api-insights
    docker-compose down -v
    docker-compose up --build
    ```
4. Access UI to create a new service and upload some specs at http://localhost:3000/
5. Confirm API works as expected, e.g. http://localhost:8081/v1/apiregistry/services
6. In IDE settings, set API Insights Endpoint URL to http://localhost:8081/v1/apiregistry/

Now everything is supposed to work as expected.

**Comment by netcicd** [comment] 2023-03-07 06:58
did exactly as stated above:
cd api-insights
mark:~/api-insights$ git pull
Already up to date.
docker-compose down -v
docker-compose up --build

now see attached logfile
[api-insights.log](https://github.com/cisco-developer/api-insights/files/10906253/api-insights.log)

closed vscode (on ubuntu). opened VSCode
created spec
check API: 

0 |  
id | "8e47e2e6-bcb4-11ed-8d30-0242ac130003"
additional_info | {}
contact |  
email | "33@33.com"
description | "bis"
name_id | "bis"
organization_id | "bis"
product_tag | "portal"
title | "bis"
visibility | "public"
created_at | "2023-03-07T06:51:58.556Z"
updated_at | "2023-03-07T06:52:23.158Z"
summary |  
score | 100
version | "0.0.1"
revision | "beta"
updated_at | "2023-03-07T06:52:23.149253613Z"

Can see spec in VSCode, can load/view but cannot edit (padlock symbol)
when I open the same spec file in VSCode, I get a Request failed with status code 405

**Comment by netcicd** [comment] 2023-03-08 06:56
retry after docker system prune and removal of the volumes, containers and images gives the same error

**Comment by xinjixi** [comment] 2023-03-08 07:52
Hi @netcicd, thanks for the feedback. 

We've identified `405` issue on IDE side, team is working on it.

**Comment by xinjixi** [comment] 2023-03-10 15:04
Hi @netcicd , the 405 issue has been fixed on IDE side, could you please install the VS extension v0.2.3 n try again?

**Comment by myref** [comment] 2023-03-13 15:48
yep. no longer showing up!

**Comment by xinjixi** [comment] 2023-03-14 01:34
> after rebooting my PC several times, I now get the APIinsights plugin to report the status and I can view the report. If I open it in the editor I cannot edit however. Is that as planned?

Yes, it's in read-only mode by design, you can click the pencil button to edit the spec on top right corner in the IDE. We'll refine the UX later if needed.

Closing this issue as the 405 issue has been solved.

**Closed** 2023-03-14 01:35 UTC
